### ISSUE TITLE
LEDs fail to work

### ISSUE THREAD

**Issue by alexellis** [CisecoPlc/PiLite#8]
I've bought 4 or 5 units from Pimoroni of the Pi-Liter and only the two middle LEDs work when the GPIO pins are set to high.

The 1st LED is always half-lit.

What is wrong with the product when used  with a PI Zero?

A gist with a code example https://gist.github.com/alexellis/3840203f8463fef438ea9dd38cb6c7fd

**Comment by toldcodger** [comment]
Hi, I think this page is about the Pi-Lite.  The Pi-Lite has 126 leds in a 14 * 9 grid.  If yours is the Ciseco Pi-LITEr that has 8 leds.  Have you seen this article. 
http://www.averagemanvsraspberrypi.com/2014/04/how-to-use-pi-liter-from-ciseco.html
If it’s the correct product it may help you test the board.

**Comment by alexellis** [comment]
I got it to work eventually. Closing the thread due to age.
